#!/usr/bin/env node
// Generates Android string resources from the canonical catalog.
//   node gen-android.mjs <output-res-dir>
// Sources per locale: strings/catalog.<locale>.json merged with every
// strings/fragments/*.<locale>.json (duplicate keys across files = hard error).
// Emits <output-res-dir>/values/strings.xml (en) and values-<locale>/strings.xml for
// every other locale. Pure Node, no dependencies. Exits non-zero on key-parity mismatch.
import { mkdirSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';
import {
  CANONICAL_LOCALE,
  assertKeyParity,
  discoverLocales,
  extractPlaceholders,
  loadCatalog,
  parseIcuPlural,
} from './lib.mjs';

const outDir = process.argv[2];
if (!outDir) {
  console.error('Usage: node gen-android.mjs <output-res-dir>');
  process.exit(1);
}

const locales = discoverLocales();
const catalogs = Object.fromEntries(locales.map((l) => [l, loadCatalog(l)]));
assertKeyParity(catalogs);

/** samaroh key "common.action.save" -> android resource name "common_action_save" */
const androidName = (key) => key.replace(/[.\-]/g, '_');

/** Escape text for an Android string resource value. */
function androidEscape(text) {
  return text
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/'/g, "\\'")
    .replace(/"/g, '\\"')
    .replace(/\n/g, '\\n');
}

/**
 * Replace named ICU placeholders with Android positional args (%1$s, %2$s, ...).
 * Position order comes from the ENGLISH value of the same key, so a placeholder keeps
 * the same position in every locale even when word order differs.
 * A string that carries args is format-processed by Android, so literal `%` must be
 * escaped as `%%` (done BEFORE substitution — placeholders are brace-delimited).
 */
function toPositional(text, order) {
  let out = text;
  if (order.length > 0) out = out.replace(/%/g, '%%');
  order.forEach((name, i) => {
    out = out.split(`{${name}}`).join(`%${i + 1}$s`);
  });
  return out;
}

const PLURAL_ORDER = ['zero', 'one', 'two', 'few', 'many', 'other'];

for (const locale of locales) {
  const dir = join(outDir, locale === CANONICAL_LOCALE ? 'values' : `values-${locale}`);
  mkdirSync(dir, { recursive: true });

  const lines = ['<?xml version="1.0" encoding="utf-8"?>', '<!-- GENERATED by samaroh-shared/codegen/gen-android.mjs — DO NOT EDIT. -->', '<resources>'];

  for (const [key, entry] of Object.entries(catalogs[CANONICAL_LOCALE])) {
    const name = androidName(key);
    const localized = catalogs[locale][key].value;
    const enPlural = parseIcuPlural(entry.value);

    if (enPlural) {
      const plural = parseIcuPlural(localized);
      if (!plural) {
        console.error(`ERROR: key "${key}" is a plural in ${CANONICAL_LOCALE} but not in ${locale}`);
        process.exit(1);
      }
      // The count arg is always Android position 1 (%1$d). Any other named placeholders
      // take positions 2..n in English first-appearance order.
      const extraOrder = extractPlaceholders(enPlural.forms.other).filter((p) => p !== enPlural.arg);
      lines.push(`    <plurals name="${name}">`);
      for (const quantity of PLURAL_ORDER) {
        if (!(quantity in plural.forms)) continue;
        let form = plural.forms[quantity].trim().replace(/%/g, '%%');
        form = form.replaceAll('#', '%1$d').split(`{${plural.arg}}`).join('%1$d');
        extraOrder.forEach((p, i) => {
          form = form.split(`{${p}}`).join(`%${i + 2}$s`);
        });
        lines.push(`        <item quantity="${quantity}">${androidEscape(form)}</item>`);
      }
      lines.push('    </plurals>');
    } else {
      const order = extractPlaceholders(entry.value); // English defines positions
      lines.push(`    <string name="${name}">${androidEscape(toPositional(localized, order))}</string>`);
    }
  }

  lines.push('</resources>', '');
  const file = join(dir, 'strings.xml');
  writeFileSync(file, lines.join('\n'), 'utf8');
  console.log(`wrote ${file} (${Object.keys(catalogs[locale]).length} keys)`);
}
